# -*- perl -*-
$pdf_mode = 5;
$xelatex = 'xelatex -interaction=nonstopmode -file-line-error -halt-on-error %O %S';

$out_dir = '../../../build/primary/math';

@default_files = qw( times_table.tex add_table.tex );

1;
